-- MySQL Script generated by MySQL Workbench
-- 02/05/18 19:23:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gosport
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gosport` ;

-- -----------------------------------------------------
-- Schema gosport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gosport` DEFAULT CHARACTER SET utf8 ;
USE `gosport` ;

-- -----------------------------------------------------
-- Table `gosport`.`centros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gosport`.`centros` ;

CREATE TABLE IF NOT EXISTS `gosport`.`centros` (
  `id_centro` INT(5) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(9) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `municipio` VARCHAR(30) NULL DEFAULT NULL,
  `provincia` VARCHAR(30) NULL DEFAULT NULL,
  `pais` VARCHAR(30) NULL DEFAULT NULL,
  `coordenada_x` VARCHAR(45) NULL DEFAULT NULL,
  `coordenada_y` VARCHAR(45) NULL DEFAULT NULL,
  `url_img` VARCHAR(60) NULL DEFAULT NULL,
  `tags` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id_centro`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gosport`.`deportes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gosport`.`deportes` ;

CREATE TABLE IF NOT EXISTS `gosport`.`deportes` (
  `id_deporte` INT(5) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `tags` VARCHAR(250) NULL DEFAULT NULL,
  `icono_full` VARCHAR(150) NULL DEFAULT NULL,
  `icono_empty` VARCHAR(45) NULL DEFAULT NULL,
  `imagen` VARCHAR(150) NULL DEFAULT NULL,
  `color` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_deporte`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gosport`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gosport`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `gosport`.`usuarios` (
  `id_usuario` INT(15) NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido1` VARCHAR(45) NULL DEFAULT NULL,
  `apellido2` VARCHAR(45) NULL DEFAULT NULL,
  `fechaAlta` DATE NULL DEFAULT NULL,
  `nick` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(250) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_usuario` ENUM('deportista', 'entrenador', 'gerente') NULL DEFAULT NULL,
  `id_centro_administrado` INT(5) NULL DEFAULT NULL,
  `foto` VARCHAR(60) NULL,
  `ultima_visita` DATE NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  INDEX `fk_usuarios_centros1_idx` (`id_centro_administrado` ASC),
  CONSTRAINT `fk_usuarios_centros1`
    FOREIGN KEY (`id_centro_administrado`)
    REFERENCES `gosport`.`centros` (`id_centro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gosport`.`eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gosport`.`eventos` ;

CREATE TABLE IF NOT EXISTS `gosport`.`eventos` (
  `id_deporte` INT(5) NOT NULL,
  `id_entrenador` INT(15) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `precio` DECIMAL(6,2) NOT NULL,
  `descripcion` VARCHAR(250) NULL DEFAULT NULL,
  `plazas` INT(4) NOT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `municipio` VARCHAR(30) NULL DEFAULT NULL,
  `provincia` VARCHAR(30) NULL DEFAULT NULL,
  `pais` VARCHAR(30) NULL DEFAULT NULL,
  `coordenada_x` VARCHAR(45) NULL DEFAULT NULL,
  `coordenada_y` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_deporte`, `id_entrenador`, `fecha`, `hora_inicio`),
  INDEX `fk_Deporte_Usuario_Usuario1_idx` (`id_entrenador` ASC),
  INDEX `fk_Deporte_Usuario_Deporte1_idx` (`id_deporte` ASC),
  CONSTRAINT `fk_Deporte_Usuario_Deporte1`
    FOREIGN KEY (`id_deporte`)
    REFERENCES `gosport`.`deportes` (`id_deporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Deporte_Usuario_Usuario1`
    FOREIGN KEY (`id_entrenador`)
    REFERENCES `gosport`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gosport`.`imagenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gosport`.`imagenes` ;

CREATE TABLE IF NOT EXISTS `gosport`.`imagenes` (
  `id_imagen` INT(11) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(80) NOT NULL,
  `titulo` VARCHAR(50) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_imagen`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gosport`.`participantes_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gosport`.`participantes_evento` ;

CREATE TABLE IF NOT EXISTS `gosport`.`participantes_evento` (
  `eventos_id_deporte` INT(5) NOT NULL,
  `eventos_id_entrenador` INT(5) NOT NULL,
  `eventos_fecha` DATE NOT NULL,
  `eventos_hora_inicio` TIME NOT NULL,
  `participante_id_usuario` INT(15) NOT NULL,
  PRIMARY KEY (`eventos_id_deporte`, `eventos_id_entrenador`, `eventos_fecha`, `eventos_hora_inicio`, `participante_id_usuario`),
  INDEX `fk_%stable_usuarios_usuarios2_idx` (`participante_id_usuario` ASC),
  INDEX `fk_%stable_usuarios_eventos1_idx` (`eventos_id_deporte` ASC, `eventos_id_entrenador` ASC, `eventos_fecha` ASC, `eventos_hora_inicio` ASC),
  CONSTRAINT `fk_%stable_usuarios_eventos1`
    FOREIGN KEY (`eventos_id_deporte` , `eventos_id_entrenador` , `eventos_fecha` , `eventos_hora_inicio`)
    REFERENCES `gosport`.`eventos` (`id_deporte` , `id_entrenador` , `fecha` , `hora_inicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_%stable_usuarios_usuarios2`
    FOREIGN KEY (`participante_id_usuario`)
    REFERENCES `gosport`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gosport`.`pistas_deporte_centro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gosport`.`pistas_deporte_centro` ;

CREATE TABLE IF NOT EXISTS `gosport`.`pistas_deporte_centro` (
  `id_deporte` INT(5) NOT NULL,
  `id_centro` INT(5) NOT NULL,
  `numero_pista` INT(3) NOT NULL,
  `precio_hora` DECIMAL(6,2) NOT NULL,
  `hora_apertura` TIME NULL DEFAULT NULL,
  `hora_cierre` TIME NULL DEFAULT NULL,
  `votos` INT(11) NULL DEFAULT NULL,
  `puntuacion_total` INT(11) NULL DEFAULT NULL,
  `url_img` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id_deporte`, `id_centro`, `numero_pista`),
  INDEX `fk_Deporte_Centro_Centro1_idx` (`id_centro` ASC),
  INDEX `fk_Deporte_Centro_Deporte_idx` (`id_deporte` ASC),
  CONSTRAINT `fk_Deporte_Centro_Centro1`
    FOREIGN KEY (`id_centro`)
    REFERENCES `gosport`.`centros` (`id_centro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Deporte_Centro_Deporte`
    FOREIGN KEY (`id_deporte`)
    REFERENCES `gosport`.`deportes` (`id_deporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gosport`.`reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gosport`.`reservas` ;

CREATE TABLE IF NOT EXISTS `gosport`.`reservas` (
  `id_deporte` INT(5) NOT NULL,
  `id_centro` INT(5) NOT NULL,
  `numero_pista` INT(3) NOT NULL,
  `id_usuario` INT(15) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora_inicio_reserva` TIME NOT NULL,
  `hora_fin_reserva` TIME NULL DEFAULT NULL,
  `precio` DECIMAL(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_deporte`, `id_centro`, `numero_pista`, `id_usuario`, `fecha`, `hora_inicio_reserva`),
  INDEX `fk_pistas_deporte_centro_has_usuarios_usuarios1_idx` (`id_usuario` ASC),
  INDEX `fk_pistas_deporte_centro_has_usuarios_pistas_deporte_centro_idx` (`id_deporte` ASC, `id_centro` ASC, `numero_pista` ASC),
  CONSTRAINT `fk_pistas_deporte_centro_has_usuarios_pistas_deporte_centro1`
    FOREIGN KEY (`id_deporte` , `id_centro` , `numero_pista`)
    REFERENCES `gosport`.`pistas_deporte_centro` (`id_deporte` , `id_centro` , `numero_pista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pistas_deporte_centro_has_usuarios_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gosport`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
